### ISSUE TITLE
How to do verbose logging?

### ISSUE THREAD

**Issue by reavessm** [vikpe/twitch-chatbot#2]
I have a setup that works on my desktop, then I packaged it into a container and the container works on my machine.  The problem, however, is when I run it on my OpenShift cluster, it runs the OnStarted func, but not the OnConnected.

How can I get more verbose logging to see WHY it's not connecting?

**Comment by vikpe** [comment]
Apparently there is no easy way to [determine failed joins/connects](https://github.com/gempir/go-twitch-irc/issues/183).
